force-app/main/default/objects/PLANS__c/PLANS__c.object-meta.xml
<CustomObject>
    <description>Travellig detail</description>
    <label>PLAN</label>
    <nameField>
        <label>PLan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PLANS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PLANS__c/fields/Travel_Hour__c.field-meta.xml
<CustomField>
    <fullName>Travel_Hour__c</fullName>
    <label>Travel Hour</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PLANS__c/fields/Travel_Locations__c.field-meta.xml
<CustomField>
    <fullName>Travel_Locations__c</fullName>
    <label>Travel Locations</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/totaltravellingTest.cls
@isTest
private class totaltravellingTest {
    @isTest
    private static void totaltravellingTestMethod(){
          PLANS__c Plan = new PLANS__c();
        Plan.Travel_Hour__c = 4;
        Plan.Travel_Locations__c ='A';
        insert Plan;
                  PLANS__c Planf = new PLANS__c();
        Planf.Travel_Hour__c = 3;
        Planf.Travel_Locations__c ='F';
        insert Planf;
        
        List<PLANS__c> PlanNew =[SELECT Id,Travel_Hour__c FROM PLANS__c where Travel_Locations__c INCLUDES ('A','F')];
        Decimal TotalHour = TotalTravelling.createMethod();
        system.assertEquals(TotalHour, PlanNew[0].Travel_Hour__c + PlanNew[1].Travel_Hour__c);
        
    } 
    
}