force-app/main/default/objects/PLANS__c/PLANS__c.object-meta.xml
<CustomObject>
    <description>Travellig detail</description>
    <label>PLAN</label>
    <nameField>
        <label>PLan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PLANS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PLANS__c/fields/Travel_Hour__c.field-meta.xml
<CustomField>
    <fullName>Travel_Hour__c</fullName>
    <label>Travel Hour</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PLANS__c/fields/Travel_Locations__c.field-meta.xml
<CustomField>
    <fullName>Travel_Locations__c</fullName>
    <label>Travel Locations</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TotalTravelling.cls
public class TotalTravelling {
    public static Decimal createMethod(){
        List<PLANS__c> PlanList = new List<PLANS__c>();
        PLanList =[SELECT Id,Travel_Hour__c FROM PLANS__c where Travel_Locations__c INCLUDES('A','F')];
        system.debug('PLanList:::'+PLanList);
        
        Decimal totelhours = 0;
        for(PLANS__c p: PlanList){
            totelhours = totelhours + p.Travel_Hour__c;
            
        }
        System.debug(totelhours);
        return totelhours;
    }
}